RUNNING: "python -m dask_cuda.cli.dask_cuda_worker --rmm-pool-size=12G
             --local-directory=/tmp/
             --scheduler-file=/root/work/cugraph/mg_utils/dask-scheduler.json
             --memory-limit=auto
             --device-memory-limit=auto
            "
2023-06-22 21:06:50,427 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.33.227.169:36283'
2023-06-22 21:06:50,431 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.33.227.169:39179'
2023-06-22 21:06:50,432 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.33.227.169:44527'
2023-06-22 21:06:50,435 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.33.227.169:44881'
2023-06-22 21:06:50,437 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.33.227.169:42363'
2023-06-22 21:06:50,440 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.33.227.169:36233'
2023-06-22 21:06:50,442 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.33.227.169:46131'
2023-06-22 21:06:50,445 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.33.227.169:35827'
2023-06-22 21:06:51,864 - distributed.preloading - INFO - Creating preload: dask_cuda.initialize
2023-06-22 21:06:51,864 - distributed.preloading - INFO - Import preload module: dask_cuda.initialize
2023-06-22 21:06:52,006 - distributed.preloading - INFO - Creating preload: dask_cuda.initialize
2023-06-22 21:06:52,006 - distributed.preloading - INFO - Creating preload: dask_cuda.initialize
2023-06-22 21:06:52,007 - distributed.preloading - INFO - Import preload module: dask_cuda.initialize
2023-06-22 21:06:52,007 - distributed.preloading - INFO - Import preload module: dask_cuda.initialize
2023-06-22 21:06:52,007 - distributed.preloading - INFO - Creating preload: dask_cuda.initialize
2023-06-22 21:06:52,007 - distributed.preloading - INFO - Import preload module: dask_cuda.initialize
2023-06-22 21:06:52,025 - distributed.preloading - INFO - Creating preload: dask_cuda.initialize
2023-06-22 21:06:52,025 - distributed.preloading - INFO - Import preload module: dask_cuda.initialize
2023-06-22 21:06:52,027 - distributed.preloading - INFO - Creating preload: dask_cuda.initialize
2023-06-22 21:06:52,028 - distributed.preloading - INFO - Import preload module: dask_cuda.initialize
2023-06-22 21:06:52,028 - distributed.preloading - INFO - Creating preload: dask_cuda.initialize
2023-06-22 21:06:52,028 - distributed.preloading - INFO - Import preload module: dask_cuda.initialize
2023-06-22 21:06:52,052 - distributed.preloading - INFO - Creating preload: dask_cuda.initialize
2023-06-22 21:06:52,052 - distributed.preloading - INFO - Import preload module: dask_cuda.initialize
2023-06-22 21:06:52,267 - distributed.preloading - INFO - Run preload setup: dask_cuda.initialize
2023-06-22 21:06:52,445 - distributed.preloading - INFO - Run preload setup: dask_cuda.initialize
2023-06-22 21:06:52,449 - distributed.preloading - INFO - Run preload setup: dask_cuda.initialize
2023-06-22 21:06:52,472 - distributed.preloading - INFO - Run preload setup: dask_cuda.initialize
2023-06-22 21:06:52,478 - distributed.preloading - INFO - Run preload setup: dask_cuda.initialize
2023-06-22 21:06:52,482 - distributed.preloading - INFO - Run preload setup: dask_cuda.initialize
2023-06-22 21:06:52,491 - distributed.preloading - INFO - Run preload setup: dask_cuda.initialize
2023-06-22 21:06:52,519 - distributed.preloading - INFO - Run preload setup: dask_cuda.initialize
2023-06-22 21:06:53,447 - distributed.worker - INFO -       Start worker at:  tcp://10.33.227.169:43505
2023-06-22 21:06:53,447 - distributed.worker - INFO -          Listening to:  tcp://10.33.227.169:43505
2023-06-22 21:06:53,447 - distributed.worker - INFO -          dashboard at:        10.33.227.169:38331
2023-06-22 21:06:53,447 - distributed.worker - INFO - Waiting to connect to:   tcp://10.33.227.169:8786
2023-06-22 21:06:53,447 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 21:06:53,447 - distributed.worker - INFO -               Threads:                          1
2023-06-22 21:06:53,447 - distributed.worker - INFO -                Memory:                  62.97 GiB
2023-06-22 21:06:53,447 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-nwhdplpa
2023-06-22 21:06:53,448 - distributed.worker - INFO - Starting Worker plugin PreImport-ff4665ae-1259-4f45-bf34-6ecd42b416e8
2023-06-22 21:06:53,448 - distributed.worker - INFO - Starting Worker plugin CPUAffinity-f81990d0-201b-4e7c-9772-8f368aea6363
2023-06-22 21:06:53,448 - distributed.worker - INFO - Starting Worker plugin RMMSetup-c997afae-6fd8-4370-9a6c-389876fb9741
2023-06-22 21:06:54,072 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 21:06:54,389 - distributed.worker - INFO -         Registered to:   tcp://10.33.227.169:8786
2023-06-22 21:06:54,389 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 21:06:54,390 - distributed.core - INFO - Starting established connection to tcp://10.33.227.169:8786
2023-06-22 21:06:54,649 - distributed.worker - INFO -       Start worker at:  tcp://10.33.227.169:42983
2023-06-22 21:06:54,649 - distributed.worker - INFO -          Listening to:  tcp://10.33.227.169:42983
2023-06-22 21:06:54,650 - distributed.worker - INFO -          dashboard at:        10.33.227.169:46313
2023-06-22 21:06:54,650 - distributed.worker - INFO - Waiting to connect to:   tcp://10.33.227.169:8786
2023-06-22 21:06:54,650 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 21:06:54,650 - distributed.worker - INFO -               Threads:                          1
2023-06-22 21:06:54,650 - distributed.worker - INFO -       Start worker at:  tcp://10.33.227.169:46075
2023-06-22 21:06:54,650 - distributed.worker - INFO -          Listening to:  tcp://10.33.227.169:46075
2023-06-22 21:06:54,650 - distributed.worker - INFO -                Memory:                  62.97 GiB
2023-06-22 21:06:54,650 - distributed.worker - INFO -          dashboard at:        10.33.227.169:37481
2023-06-22 21:06:54,650 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-aetzqj6q
2023-06-22 21:06:54,650 - distributed.worker - INFO - Waiting to connect to:   tcp://10.33.227.169:8786
2023-06-22 21:06:54,650 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 21:06:54,650 - distributed.worker - INFO -               Threads:                          1
2023-06-22 21:06:54,650 - distributed.worker - INFO -                Memory:                  62.97 GiB
2023-06-22 21:06:54,650 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-sx6mh9kz
2023-06-22 21:06:54,651 - distributed.worker - INFO - Starting Worker plugin PreImport-48ea3219-f046-482d-8882-138e9c0ac232
2023-06-22 21:06:54,651 - distributed.worker - INFO - Starting Worker plugin PreImport-d8bfe24f-d17c-42b9-87b3-315f5cad340c
2023-06-22 21:06:54,651 - distributed.worker - INFO - Starting Worker plugin CPUAffinity-a24a7e30-9804-431f-b266-5757db419016
2023-06-22 21:06:54,651 - distributed.worker - INFO - Starting Worker plugin CPUAffinity-b9c091f2-c56f-44c5-b507-e9b6d954598a
2023-06-22 21:06:54,651 - distributed.worker - INFO - Starting Worker plugin RMMSetup-6f2f4e53-048d-4b34-b0bb-59b14ef2d2bc
2023-06-22 21:06:54,651 - distributed.worker - INFO - Starting Worker plugin RMMSetup-12c8ad99-4739-41bf-a627-ad87da2dd33d
2023-06-22 21:06:54,739 - distributed.worker - INFO -       Start worker at:  tcp://10.33.227.169:43439
2023-06-22 21:06:54,739 - distributed.worker - INFO -          Listening to:  tcp://10.33.227.169:43439
2023-06-22 21:06:54,739 - distributed.worker - INFO -          dashboard at:        10.33.227.169:35751
2023-06-22 21:06:54,739 - distributed.worker - INFO - Waiting to connect to:   tcp://10.33.227.169:8786
2023-06-22 21:06:54,739 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 21:06:54,740 - distributed.worker - INFO -               Threads:                          1
2023-06-22 21:06:54,740 - distributed.worker - INFO -                Memory:                  62.97 GiB
2023-06-22 21:06:54,740 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-g2xc7367
2023-06-22 21:06:54,741 - distributed.worker - INFO - Starting Worker plugin RMMSetup-9960391f-993b-40ca-a06c-79f0a6a93638
2023-06-22 21:06:54,742 - distributed.worker - INFO -       Start worker at:  tcp://10.33.227.169:38609
2023-06-22 21:06:54,742 - distributed.worker - INFO -          Listening to:  tcp://10.33.227.169:38609
2023-06-22 21:06:54,742 - distributed.worker - INFO -          dashboard at:        10.33.227.169:35473
2023-06-22 21:06:54,742 - distributed.worker - INFO - Waiting to connect to:   tcp://10.33.227.169:8786
2023-06-22 21:06:54,742 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 21:06:54,743 - distributed.worker - INFO -               Threads:                          1
2023-06-22 21:06:54,743 - distributed.worker - INFO -                Memory:                  62.97 GiB
2023-06-22 21:06:54,743 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-gakepndj
2023-06-22 21:06:54,743 - distributed.worker - INFO - Starting Worker plugin RMMSetup-d9c0f99d-fa2d-4ab9-aac6-c26331695544
2023-06-22 21:06:54,759 - distributed.worker - INFO -       Start worker at:  tcp://10.33.227.169:43527
2023-06-22 21:06:54,759 - distributed.worker - INFO -          Listening to:  tcp://10.33.227.169:43527
2023-06-22 21:06:54,759 - distributed.worker - INFO -          dashboard at:        10.33.227.169:46337
2023-06-22 21:06:54,759 - distributed.worker - INFO -       Start worker at:  tcp://10.33.227.169:33287
2023-06-22 21:06:54,759 - distributed.worker - INFO - Waiting to connect to:   tcp://10.33.227.169:8786
2023-06-22 21:06:54,759 - distributed.worker - INFO -          Listening to:  tcp://10.33.227.169:33287
2023-06-22 21:06:54,759 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 21:06:54,759 - distributed.worker - INFO -               Threads:                          1
2023-06-22 21:06:54,759 - distributed.worker - INFO -          dashboard at:        10.33.227.169:40895
2023-06-22 21:06:54,759 - distributed.worker - INFO - Waiting to connect to:   tcp://10.33.227.169:8786
2023-06-22 21:06:54,759 - distributed.worker - INFO -                Memory:                  62.97 GiB
2023-06-22 21:06:54,759 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 21:06:54,759 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-ypxprco1
2023-06-22 21:06:54,759 - distributed.worker - INFO -               Threads:                          1
2023-06-22 21:06:54,759 - distributed.worker - INFO -                Memory:                  62.97 GiB
2023-06-22 21:06:54,759 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-y21e2qyl
2023-06-22 21:06:54,760 - distributed.worker - INFO - Starting Worker plugin PreImport-7f39d1f9-1f7c-46ef-8fdb-36c0fb52d74d
2023-06-22 21:06:54,760 - distributed.worker - INFO - Starting Worker plugin CPUAffinity-643d7dc2-7cf1-4bdc-b9bf-8ee6ed8d4ddc
2023-06-22 21:06:54,760 - distributed.worker - INFO - Starting Worker plugin PreImport-8b39f2a1-03f1-4a13-987f-c5c0c93deabf
2023-06-22 21:06:54,760 - distributed.worker - INFO - Starting Worker plugin CPUAffinity-275517f1-ea04-4486-9e5f-b1ee53de5d30
2023-06-22 21:06:54,760 - distributed.worker - INFO - Starting Worker plugin RMMSetup-b76b5324-bebd-41fc-abca-78dd5e6772cd
2023-06-22 21:06:54,760 - distributed.worker - INFO - Starting Worker plugin RMMSetup-3c724e92-9f6c-4fdb-bf05-eb6625fff8bb
2023-06-22 21:06:54,761 - distributed.worker - INFO -       Start worker at:  tcp://10.33.227.169:37343
2023-06-22 21:06:54,761 - distributed.worker - INFO -          Listening to:  tcp://10.33.227.169:37343
2023-06-22 21:06:54,761 - distributed.worker - INFO -          dashboard at:        10.33.227.169:33603
2023-06-22 21:06:54,761 - distributed.worker - INFO - Waiting to connect to:   tcp://10.33.227.169:8786
2023-06-22 21:06:54,761 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 21:06:54,761 - distributed.worker - INFO -               Threads:                          1
2023-06-22 21:06:54,761 - distributed.worker - INFO -                Memory:                  62.97 GiB
2023-06-22 21:06:54,761 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-yv7835q1
2023-06-22 21:06:54,762 - distributed.worker - INFO - Starting Worker plugin RMMSetup-60d28464-d038-4cea-b449-6f76f984d4a2
2023-06-22 21:06:54,797 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 21:06:54,797 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 21:06:54,806 - distributed.worker - INFO -         Registered to:   tcp://10.33.227.169:8786
2023-06-22 21:06:54,806 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 21:06:54,807 - distributed.worker - INFO -         Registered to:   tcp://10.33.227.169:8786
2023-06-22 21:06:54,807 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 21:06:54,807 - distributed.core - INFO - Starting established connection to tcp://10.33.227.169:8786
2023-06-22 21:06:54,809 - distributed.core - INFO - Starting established connection to tcp://10.33.227.169:8786
2023-06-22 21:06:54,882 - distributed.worker - INFO - Starting Worker plugin PreImport-d7542fba-bb1e-441c-a309-f86ee4d66e32
2023-06-22 21:06:54,882 - distributed.worker - INFO - Starting Worker plugin CPUAffinity-9da03659-9180-4d02-bddd-d736ef32087d
2023-06-22 21:06:54,883 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 21:06:54,895 - distributed.worker - INFO -         Registered to:   tcp://10.33.227.169:8786
2023-06-22 21:06:54,895 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 21:06:54,897 - distributed.core - INFO - Starting established connection to tcp://10.33.227.169:8786
2023-06-22 21:06:54,946 - distributed.worker - INFO - Starting Worker plugin PreImport-801a14d8-4c53-4829-8c4a-9db042e8fc48
2023-06-22 21:06:54,946 - distributed.worker - INFO - Starting Worker plugin CPUAffinity-4591d238-6718-4bd9-9698-55e289a15be8
2023-06-22 21:06:54,946 - distributed.worker - INFO - Starting Worker plugin CPUAffinity-e1915589-2504-4958-9950-b576dbed939e
2023-06-22 21:06:54,946 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 21:06:54,946 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 21:06:54,947 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 21:06:54,950 - distributed.worker - INFO - Starting Worker plugin PreImport-cba84f7d-9982-4c0b-89c9-b5b3b7e812df
2023-06-22 21:06:54,951 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 21:06:54,955 - distributed.worker - INFO -         Registered to:   tcp://10.33.227.169:8786
2023-06-22 21:06:54,955 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 21:06:54,956 - distributed.core - INFO - Starting established connection to tcp://10.33.227.169:8786
2023-06-22 21:06:54,957 - distributed.worker - INFO -         Registered to:   tcp://10.33.227.169:8786
2023-06-22 21:06:54,957 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 21:06:54,958 - distributed.core - INFO - Starting established connection to tcp://10.33.227.169:8786
2023-06-22 21:06:54,960 - distributed.worker - INFO -         Registered to:   tcp://10.33.227.169:8786
2023-06-22 21:06:54,960 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 21:06:54,962 - distributed.core - INFO - Starting established connection to tcp://10.33.227.169:8786
2023-06-22 21:06:54,963 - distributed.worker - INFO -         Registered to:   tcp://10.33.227.169:8786
2023-06-22 21:06:54,963 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 21:06:54,965 - distributed.core - INFO - Starting established connection to tcp://10.33.227.169:8786
2023-06-22 21:06:57,660 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 21:06:57,660 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 21:06:57,660 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 21:06:57,661 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 21:06:57,661 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 21:06:57,661 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 21:06:57,665 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 21:06:57,667 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 21:06:57,761 - distributed.worker - INFO - Run out-of-band function '_func_init_all'
2023-06-22 21:06:57,762 - distributed.worker - INFO - Run out-of-band function '_func_init_all'
2023-06-22 21:06:57,762 - distributed.worker - INFO - Run out-of-band function '_func_init_all'
2023-06-22 21:06:57,762 - distributed.worker - INFO - Run out-of-band function '_func_init_all'
2023-06-22 21:06:57,762 - distributed.worker - INFO - Run out-of-band function '_func_init_all'
2023-06-22 21:06:57,762 - distributed.worker - INFO - Run out-of-band function '_func_init_all'
2023-06-22 21:06:57,762 - distributed.worker - INFO - Run out-of-band function '_func_init_all'
2023-06-22 21:06:57,762 - distributed.worker - INFO - Run out-of-band function '_func_init_all'
2023-06-22 21:07:08,792 - distributed.worker - INFO - Run out-of-band function '_subcomm_init'
2023-06-22 21:07:08,804 - distributed.worker - INFO - Run out-of-band function '_subcomm_init'
2023-06-22 21:07:08,850 - distributed.worker - INFO - Run out-of-band function '_subcomm_init'
2023-06-22 21:07:08,999 - distributed.worker - INFO - Run out-of-band function '_subcomm_init'
2023-06-22 21:07:09,004 - distributed.worker - INFO - Run out-of-band function '_subcomm_init'
2023-06-22 21:07:09,034 - distributed.worker - INFO - Run out-of-band function '_subcomm_init'
2023-06-22 21:07:09,184 - distributed.worker - INFO - Run out-of-band function '_subcomm_init'
2023-06-22 21:07:09,485 - distributed.worker - INFO - Run out-of-band function '_subcomm_init'
2023-06-22 21:07:15,643 - distributed.core - INFO - Event loop was unresponsive in Worker for 16.23s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2023-06-22 21:07:15,643 - distributed.core - INFO - Event loop was unresponsive in Worker for 16.23s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2023-06-22 21:07:15,644 - distributed.core - INFO - Event loop was unresponsive in Worker for 16.22s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2023-06-22 21:07:15,644 - distributed.core - INFO - Event loop was unresponsive in Worker for 16.23s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2023-06-22 21:07:15,739 - distributed.core - INFO - Event loop was unresponsive in Worker for 16.32s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2023-06-22 21:07:15,740 - distributed.core - INFO - Event loop was unresponsive in Worker for 16.32s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2023-06-22 21:07:15,740 - distributed.core - INFO - Event loop was unresponsive in Worker for 16.32s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2023-06-22 21:07:15,741 - distributed.core - INFO - Event loop was unresponsive in Worker for 16.32s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2023-06-22 21:07:48,084 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 21:07:48,084 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 21:07:48,084 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 21:07:48,088 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 21:07:48,088 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 21:07:48,088 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 21:07:48,088 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 21:07:48,088 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 21:07:52,249 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 21:07:52,249 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 21:07:52,249 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 21:07:52,249 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 21:07:52,250 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 21:07:52,250 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 21:07:52,250 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 21:07:52,250 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 21:07:52,581 - distributed.worker - WARNING - Compute Failed
Key:       _call_plc_uniform_neighbor_sample-4dfe8e49-ac20-4512-869e-e7babe3d2491
Function:  _call_plc_uniform_neighbor_sample
args:      (b'\xdd\xa3\x06q\x1a\x8cIG\xa8\x8d\xe3\xde\x18|2\x9f', <pylibcugraph.graphs.MGGraph object at 0x7f2f193b1250>, < could not convert arg to str >, True, 8, 0, 9, array([10, 25], dtype=int32), False)
kwargs:    {'weight_t': 'float32', 'with_edge_properties': True, 'random_state': 2984258459430835088, 'return_offsets': False}
Exception: "RuntimeError('non-success value returned from cugraph_uniform_neighbor_sample_with_edge_properties: CUGRAPH_UNKNOWN_ERROR for_each: failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountered')"

2023-06-22 21:07:52,584 - distributed.worker - WARNING - Compute Failed
Key:       _call_plc_uniform_neighbor_sample-29444b8d-a2f5-42f1-8dee-87ab0cbae552
Function:  _call_plc_uniform_neighbor_sample
args:      (b'\xdd\xa3\x06q\x1a\x8cIG\xa8\x8d\xe3\xde\x18|2\x9f', <pylibcugraph.graphs.MGGraph object at 0x7f8e7e5117d0>, < could not convert arg to str >, True, 8, 0, 9, array([10, 25], dtype=int32), False)
kwargs:    {'weight_t': 'float32', 'with_edge_properties': True, 'random_state': -3523382296671163337, 'return_offsets': False}
Exception: "RuntimeError('non-success value returned from cugraph_uniform_neighbor_sample_with_edge_properties: CUGRAPH_UNKNOWN_ERROR for_each: failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountered')"

2023-06-22 21:11:38,305 - distributed.worker - INFO - Stopping worker at tcp://10.33.227.169:43527. Reason: worker-handle-scheduler-connection-broken
2023-06-22 21:11:38,306 - distributed.worker - INFO - Stopping worker at tcp://10.33.227.169:46075. Reason: worker-handle-scheduler-connection-broken
2023-06-22 21:11:38,306 - distributed.nanny - INFO - Closing Nanny at 'tcp://10.33.227.169:36283'. Reason: nanny-close
2023-06-22 21:11:38,308 - distributed.nanny - INFO - Nanny asking worker to close. Reason: nanny-close
2023-06-22 21:11:38,309 - distributed.nanny - INFO - Closing Nanny at 'tcp://10.33.227.169:39179'. Reason: nanny-close
2023-06-22 21:11:38,310 - distributed.nanny - INFO - Nanny asking worker to close. Reason: nanny-close
2023-06-22 21:11:38,310 - distributed.nanny - INFO - Closing Nanny at 'tcp://10.33.227.169:42363'. Reason: nanny-close
2023-06-22 21:11:38,311 - distributed.nanny - INFO - Nanny asking worker to close. Reason: nanny-close
2023-06-22 21:11:38,311 - distributed.nanny - INFO - Closing Nanny at 'tcp://10.33.227.169:36233'. Reason: nanny-close
2023-06-22 21:11:38,311 - distributed.nanny - INFO - Nanny asking worker to close. Reason: nanny-close
2023-06-22 21:11:38,311 - distributed.nanny - INFO - Closing Nanny at 'tcp://10.33.227.169:46131'. Reason: nanny-close
2023-06-22 21:11:38,312 - distributed.nanny - INFO - Nanny asking worker to close. Reason: nanny-close
2023-06-22 21:11:38,312 - distributed.nanny - INFO - Closing Nanny at 'tcp://10.33.227.169:44527'. Reason: nanny-close
2023-06-22 21:11:38,312 - distributed.nanny - INFO - Nanny asking worker to close. Reason: nanny-close
2023-06-22 21:11:38,313 - distributed.nanny - INFO - Closing Nanny at 'tcp://10.33.227.169:44881'. Reason: nanny-close
2023-06-22 21:11:38,313 - distributed.nanny - INFO - Nanny asking worker to close. Reason: nanny-close
2023-06-22 21:11:38,313 - distributed.nanny - INFO - Closing Nanny at 'tcp://10.33.227.169:35827'. Reason: nanny-close
2023-06-22 21:11:38,313 - distributed.nanny - INFO - Nanny asking worker to close. Reason: nanny-close
2023-06-22 21:11:38,324 - distributed.worker - ERROR - Timed out during handshake while connecting to tcp://10.33.227.169:46131 after 100 s
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/base_events.py", line 1871, in _run_once
    event_list = self._selector.select(timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/selectors.py", line 469, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/core.py", line 373, in connect
    handshake = await wait_for(comm.read(), time_left())
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/utils.py", line 1878, in wait_for
    return await asyncio.wait_for(fut, timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/tcp.py", line 241, in read
    convert_stream_closed_error(self, e)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed)  local=tcp://10.33.227.169:59466 remote=tcp://10.33.227.169:46131>: ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/utils.py", line 754, in wrapper
    return await func(*args, **kwargs)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/worker.py", line 1540, in close
    await r.close_gracefully(reason=reason)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/core.py", line 1362, in send_recv_from_rpc
    comm = await self.pool.connect(self.addr)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/core.py", line 1606, in connect
    return await connect_attempt
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/core.py", line 1527, in _connect
    comm = await connect(
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/core.py", line 378, in connect
    raise OSError(
OSError: Timed out during handshake while connecting to tcp://10.33.227.169:46131 after 100 s
2023-06-22 21:11:38,335 - distributed.worker - ERROR - Timed out during handshake while connecting to tcp://10.33.227.169:35827 after 100 s
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/base_events.py", line 1871, in _run_once
    event_list = self._selector.select(timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/selectors.py", line 469, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/core.py", line 373, in connect
    handshake = await wait_for(comm.read(), time_left())
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/utils.py", line 1878, in wait_for
    return await asyncio.wait_for(fut, timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/tcp.py", line 241, in read
    convert_stream_closed_error(self, e)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed)  local=tcp://10.33.227.169:36350 remote=tcp://10.33.227.169:35827>: ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/utils.py", line 754, in wrapper
    return await func(*args, **kwargs)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/worker.py", line 1540, in close
    await r.close_gracefully(reason=reason)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/core.py", line 1362, in send_recv_from_rpc
    comm = await self.pool.connect(self.addr)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/core.py", line 1606, in connect
    return await connect_attempt
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/core.py", line 1527, in _connect
    comm = await connect(
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/core.py", line 378, in connect
    raise OSError(
OSError: Timed out during handshake while connecting to tcp://10.33.227.169:35827 after 100 s
2023-06-22 21:11:41,514 - distributed.nanny - WARNING - Worker process still alive after 3.199983367919922 seconds, killing
2023-06-22 21:11:41,515 - distributed.nanny - WARNING - Worker process still alive after 3.199999389648438 seconds, killing
2023-06-22 21:11:41,515 - distributed.nanny - WARNING - Worker process still alive after 3.1999995422363288 seconds, killing
2023-06-22 21:11:41,516 - distributed.nanny - WARNING - Worker process still alive after 3.199999389648438 seconds, killing
2023-06-22 21:11:41,517 - distributed.nanny - WARNING - Worker process still alive after 3.1999995422363288 seconds, killing
2023-06-22 21:11:41,517 - distributed.nanny - WARNING - Worker process still alive after 3.1999995422363288 seconds, killing
2023-06-22 21:11:41,517 - distributed.nanny - WARNING - Worker process still alive after 3.1999995422363288 seconds, killing
2023-06-22 21:11:41,519 - distributed.nanny - WARNING - Worker process still alive after 3.1999995422363288 seconds, killing
2023-06-22 21:11:42,309 - distributed.nanny - ERROR - Error in Nanny killing Worker subprocess
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 597, in close
    await self.kill(timeout=timeout, reason=reason)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 380, in kill
    await self.process.kill(reason=reason, timeout=0.8 * (deadline - time()))
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 853, in kill
    await process.join(max(0, deadline - time()))
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/process.py", line 330, in join
    await wait_for(asyncio.shield(self._exit_future), timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/utils.py", line 1878, in wait_for
    return await asyncio.wait_for(fut, timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
2023-06-22 21:11:42,311 - distributed.nanny - ERROR - Error in Nanny killing Worker subprocess
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 597, in close
    await self.kill(timeout=timeout, reason=reason)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 380, in kill
    await self.process.kill(reason=reason, timeout=0.8 * (deadline - time()))
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 853, in kill
    await process.join(max(0, deadline - time()))
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/process.py", line 330, in join
    await wait_for(asyncio.shield(self._exit_future), timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/utils.py", line 1878, in wait_for
    return await asyncio.wait_for(fut, timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
2023-06-22 21:11:42,312 - distributed.nanny - ERROR - Error in Nanny killing Worker subprocess
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 597, in close
    await self.kill(timeout=timeout, reason=reason)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 380, in kill
    await self.process.kill(reason=reason, timeout=0.8 * (deadline - time()))
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 853, in kill
    await process.join(max(0, deadline - time()))
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/process.py", line 330, in join
    await wait_for(asyncio.shield(self._exit_future), timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/utils.py", line 1878, in wait_for
    return await asyncio.wait_for(fut, timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
2023-06-22 21:11:42,312 - distributed.nanny - ERROR - Error in Nanny killing Worker subprocess
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 597, in close
    await self.kill(timeout=timeout, reason=reason)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 380, in kill
    await self.process.kill(reason=reason, timeout=0.8 * (deadline - time()))
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 853, in kill
    await process.join(max(0, deadline - time()))
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/process.py", line 330, in join
    await wait_for(asyncio.shield(self._exit_future), timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/utils.py", line 1878, in wait_for
    return await asyncio.wait_for(fut, timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
2023-06-22 21:11:42,313 - distributed.nanny - ERROR - Error in Nanny killing Worker subprocess
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 597, in close
    await self.kill(timeout=timeout, reason=reason)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 380, in kill
    await self.process.kill(reason=reason, timeout=0.8 * (deadline - time()))
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 853, in kill
    await process.join(max(0, deadline - time()))
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/process.py", line 330, in join
    await wait_for(asyncio.shield(self._exit_future), timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/utils.py", line 1878, in wait_for
    return await asyncio.wait_for(fut, timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
2023-06-22 21:11:42,313 - distributed.nanny - ERROR - Error in Nanny killing Worker subprocess
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 597, in close
    await self.kill(timeout=timeout, reason=reason)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 380, in kill
    await self.process.kill(reason=reason, timeout=0.8 * (deadline - time()))
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 853, in kill
    await process.join(max(0, deadline - time()))
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/process.py", line 330, in join
    await wait_for(asyncio.shield(self._exit_future), timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/utils.py", line 1878, in wait_for
    return await asyncio.wait_for(fut, timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
2023-06-22 21:11:42,313 - distributed.nanny - ERROR - Error in Nanny killing Worker subprocess
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 597, in close
    await self.kill(timeout=timeout, reason=reason)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 380, in kill
    await self.process.kill(reason=reason, timeout=0.8 * (deadline - time()))
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 853, in kill
    await process.join(max(0, deadline - time()))
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/process.py", line 330, in join
    await wait_for(asyncio.shield(self._exit_future), timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/utils.py", line 1878, in wait_for
    return await asyncio.wait_for(fut, timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
2023-06-22 21:11:42,314 - distributed.nanny - ERROR - Error in Nanny killing Worker subprocess
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 597, in close
    await self.kill(timeout=timeout, reason=reason)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 380, in kill
    await self.process.kill(reason=reason, timeout=0.8 * (deadline - time()))
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 853, in kill
    await process.join(max(0, deadline - time()))
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/process.py", line 330, in join
    await wait_for(asyncio.shield(self._exit_future), timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/utils.py", line 1878, in wait_for
    return await asyncio.wait_for(fut, timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
2023-06-22 21:11:42,316 - distributed.process - INFO - reaping stray process <SpawnProcess name='Dask Worker process (from Nanny)' pid=1408123 parent=1408063 started daemon>
2023-06-22 21:11:42,316 - distributed.process - INFO - reaping stray process <SpawnProcess name='Dask Worker process (from Nanny)' pid=1408120 parent=1408063 started daemon>
2023-06-22 21:11:42,316 - distributed.process - INFO - reaping stray process <SpawnProcess name='Dask Worker process (from Nanny)' pid=1408117 parent=1408063 started daemon>
2023-06-22 21:11:42,316 - distributed.process - INFO - reaping stray process <SpawnProcess name='Dask Worker process (from Nanny)' pid=1408114 parent=1408063 started daemon>
2023-06-22 21:11:42,316 - distributed.process - INFO - reaping stray process <SpawnProcess name='Dask Worker process (from Nanny)' pid=1408111 parent=1408063 started daemon>
2023-06-22 21:11:42,316 - distributed.process - INFO - reaping stray process <SpawnProcess name='Dask Worker process (from Nanny)' pid=1408107 parent=1408063 started daemon>
2023-06-22 21:11:42,316 - distributed.process - INFO - reaping stray process <SpawnProcess name='Dask Worker process (from Nanny)' pid=1408104 parent=1408063 started daemon>
2023-06-22 21:11:42,316 - distributed.process - INFO - reaping stray process <SpawnProcess name='Dask Worker process (from Nanny)' pid=1408101 parent=1408063 started daemon>
2023-06-22 21:11:42,620 - distributed.process - WARNING - [<AsyncProcess Dask Worker process (from Nanny)>] process 1408104 exit status was already read will report exitcode 255
2023-06-22 21:11:42,716 - distributed.process - WARNING - [<AsyncProcess Dask Worker process (from Nanny)>] process 1408107 exit status was already read will report exitcode 255
