RUNNING: "python -m dask_cuda.cli.dask_cuda_worker --rmm-pool-size=12G
             --local-directory=/tmp/
             --scheduler-file=/root/work/cugraph/mg_utils/dask-scheduler.json
             --memory-limit=auto
             --device-memory-limit=auto
            "
2023-06-22 22:25:45,041 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.33.227.169:41969'
2023-06-22 22:25:45,045 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.33.227.169:39821'
2023-06-22 22:25:45,047 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.33.227.169:46059'
2023-06-22 22:25:45,049 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.33.227.169:44281'
2023-06-22 22:25:45,052 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.33.227.169:41851'
2023-06-22 22:25:45,054 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.33.227.169:42097'
2023-06-22 22:25:45,056 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.33.227.169:43831'
2023-06-22 22:25:45,059 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.33.227.169:40591'
2023-06-22 22:25:46,504 - distributed.preloading - INFO - Creating preload: dask_cuda.initialize
2023-06-22 22:25:46,504 - distributed.preloading - INFO - Import preload module: dask_cuda.initialize
2023-06-22 22:25:46,585 - distributed.preloading - INFO - Creating preload: dask_cuda.initialize
2023-06-22 22:25:46,585 - distributed.preloading - INFO - Import preload module: dask_cuda.initialize
2023-06-22 22:25:46,635 - distributed.preloading - INFO - Creating preload: dask_cuda.initialize
2023-06-22 22:25:46,635 - distributed.preloading - INFO - Import preload module: dask_cuda.initialize
2023-06-22 22:25:46,636 - distributed.preloading - INFO - Creating preload: dask_cuda.initialize
2023-06-22 22:25:46,636 - distributed.preloading - INFO - Import preload module: dask_cuda.initialize
2023-06-22 22:25:46,636 - distributed.preloading - INFO - Creating preload: dask_cuda.initialize
2023-06-22 22:25:46,636 - distributed.preloading - INFO - Import preload module: dask_cuda.initialize
2023-06-22 22:25:46,650 - distributed.preloading - INFO - Creating preload: dask_cuda.initialize
2023-06-22 22:25:46,651 - distributed.preloading - INFO - Import preload module: dask_cuda.initialize
2023-06-22 22:25:46,651 - distributed.preloading - INFO - Creating preload: dask_cuda.initialize
2023-06-22 22:25:46,651 - distributed.preloading - INFO - Import preload module: dask_cuda.initialize
2023-06-22 22:25:46,652 - distributed.preloading - INFO - Creating preload: dask_cuda.initialize
2023-06-22 22:25:46,653 - distributed.preloading - INFO - Import preload module: dask_cuda.initialize
2023-06-22 22:25:46,907 - distributed.preloading - INFO - Run preload setup: dask_cuda.initialize
2023-06-22 22:25:46,999 - distributed.preloading - INFO - Run preload setup: dask_cuda.initialize
2023-06-22 22:25:47,094 - distributed.preloading - INFO - Run preload setup: dask_cuda.initialize
2023-06-22 22:25:47,105 - distributed.preloading - INFO - Run preload setup: dask_cuda.initialize
2023-06-22 22:25:47,106 - distributed.preloading - INFO - Run preload setup: dask_cuda.initialize
2023-06-22 22:25:47,119 - distributed.preloading - INFO - Run preload setup: dask_cuda.initialize
2023-06-22 22:25:47,119 - distributed.preloading - INFO - Run preload setup: dask_cuda.initialize
2023-06-22 22:25:47,131 - distributed.preloading - INFO - Run preload setup: dask_cuda.initialize
2023-06-22 22:25:48,356 - distributed.worker - INFO -       Start worker at:  tcp://10.33.227.169:34491
2023-06-22 22:25:48,356 - distributed.worker - INFO -          Listening to:  tcp://10.33.227.169:34491
2023-06-22 22:25:48,356 - distributed.worker - INFO -          dashboard at:        10.33.227.169:41451
2023-06-22 22:25:48,356 - distributed.worker - INFO - Waiting to connect to:   tcp://10.33.227.169:8786
2023-06-22 22:25:48,356 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 22:25:48,356 - distributed.worker - INFO -               Threads:                          1
2023-06-22 22:25:48,356 - distributed.worker - INFO -                Memory:                  62.97 GiB
2023-06-22 22:25:48,356 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-azcj34sx
2023-06-22 22:25:48,357 - distributed.worker - INFO - Starting Worker plugin PreImport-97f57a6e-582f-4ffe-aee1-7a7d79822b27
2023-06-22 22:25:48,357 - distributed.worker - INFO - Starting Worker plugin CPUAffinity-de3c4a90-19f7-4f71-923c-0019a237e1a4
2023-06-22 22:25:48,357 - distributed.worker - INFO - Starting Worker plugin RMMSetup-bc5c874f-9404-4232-bab0-8b7eab5d9de7
2023-06-22 22:25:48,630 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 22:25:48,923 - distributed.worker - INFO -         Registered to:   tcp://10.33.227.169:8786
2023-06-22 22:25:48,923 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 22:25:48,925 - distributed.core - INFO - Starting established connection to tcp://10.33.227.169:8786
2023-06-22 22:25:49,320 - distributed.worker - INFO -       Start worker at:  tcp://10.33.227.169:33975
2023-06-22 22:25:49,320 - distributed.worker - INFO -       Start worker at:  tcp://10.33.227.169:42833
2023-06-22 22:25:49,327 - distributed.worker - INFO -       Start worker at:  tcp://10.33.227.169:33069
2023-06-22 22:25:49,328 - distributed.worker - INFO -          Listening to:  tcp://10.33.227.169:33975
2023-06-22 22:25:49,328 - distributed.worker - INFO -          Listening to:  tcp://10.33.227.169:42833
2023-06-22 22:25:49,328 - distributed.worker - INFO -          Listening to:  tcp://10.33.227.169:33069
2023-06-22 22:25:49,328 - distributed.worker - INFO -          dashboard at:        10.33.227.169:38991
2023-06-22 22:25:49,328 - distributed.worker - INFO -          dashboard at:        10.33.227.169:34929
2023-06-22 22:25:49,328 - distributed.worker - INFO - Waiting to connect to:   tcp://10.33.227.169:8786
2023-06-22 22:25:49,328 - distributed.worker - INFO -          dashboard at:        10.33.227.169:41893
2023-06-22 22:25:49,328 - distributed.worker - INFO - Waiting to connect to:   tcp://10.33.227.169:8786
2023-06-22 22:25:49,328 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 22:25:49,328 - distributed.worker - INFO - Waiting to connect to:   tcp://10.33.227.169:8786
2023-06-22 22:25:49,328 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 22:25:49,328 - distributed.worker - INFO -               Threads:                          1
2023-06-22 22:25:49,328 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 22:25:49,328 - distributed.worker - INFO -               Threads:                          1
2023-06-22 22:25:49,328 - distributed.worker - INFO -               Threads:                          1
2023-06-22 22:25:49,328 - distributed.worker - INFO -                Memory:                  62.97 GiB
2023-06-22 22:25:49,328 - distributed.worker - INFO -                Memory:                  62.97 GiB
2023-06-22 22:25:49,328 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-hlz7yeh_
2023-06-22 22:25:49,328 - distributed.worker - INFO -                Memory:                  62.97 GiB
2023-06-22 22:25:49,329 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-olzap7bm
2023-06-22 22:25:49,329 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-opd91o7v
2023-06-22 22:25:49,329 - distributed.worker - INFO - Starting Worker plugin PreImport-d6e845c5-57bb-4fe1-9cfe-32197ca2e285
2023-06-22 22:25:49,329 - distributed.worker - INFO - Starting Worker plugin RMMSetup-9ede8002-3a77-4f5e-8aac-b5382d59b48d
2023-06-22 22:25:49,329 - distributed.worker - INFO - Starting Worker plugin RMMSetup-34693425-95b2-4768-9059-f25a4b8a2300
2023-06-22 22:25:49,329 - distributed.worker - INFO - Starting Worker plugin CPUAffinity-f9412cbf-636c-4986-b470-ab3973e6b946
2023-06-22 22:25:49,329 - distributed.worker - INFO - Starting Worker plugin RMMSetup-821bf1ac-957e-492e-9ad4-dbd2c52a795a
2023-06-22 22:25:49,335 - distributed.worker - INFO -       Start worker at:  tcp://10.33.227.169:45315
2023-06-22 22:25:49,335 - distributed.worker - INFO -          Listening to:  tcp://10.33.227.169:45315
2023-06-22 22:25:49,335 - distributed.worker - INFO -          dashboard at:        10.33.227.169:40421
2023-06-22 22:25:49,335 - distributed.worker - INFO - Waiting to connect to:   tcp://10.33.227.169:8786
2023-06-22 22:25:49,335 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 22:25:49,335 - distributed.worker - INFO -               Threads:                          1
2023-06-22 22:25:49,335 - distributed.worker - INFO -                Memory:                  62.97 GiB
2023-06-22 22:25:49,335 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-wr3zd1md
2023-06-22 22:25:49,335 - distributed.worker - INFO - Starting Worker plugin PreImport-5c5ea073-39c0-4c01-9624-c6e57768c083
2023-06-22 22:25:49,335 - distributed.worker - INFO - Starting Worker plugin CPUAffinity-da11deee-f4d3-49cb-a34b-7f1e7629e431
2023-06-22 22:25:49,336 - distributed.worker - INFO - Starting Worker plugin RMMSetup-9d977a35-6ed3-4c59-bc39-302812d80504
2023-06-22 22:25:49,338 - distributed.worker - INFO -       Start worker at:  tcp://10.33.227.169:36975
2023-06-22 22:25:49,338 - distributed.worker - INFO -          Listening to:  tcp://10.33.227.169:36975
2023-06-22 22:25:49,339 - distributed.worker - INFO -          dashboard at:        10.33.227.169:35929
2023-06-22 22:25:49,339 - distributed.worker - INFO - Waiting to connect to:   tcp://10.33.227.169:8786
2023-06-22 22:25:49,339 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 22:25:49,339 - distributed.worker - INFO -               Threads:                          1
2023-06-22 22:25:49,339 - distributed.worker - INFO -                Memory:                  62.97 GiB
2023-06-22 22:25:49,339 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-os55kn0i
2023-06-22 22:25:49,339 - distributed.worker - INFO - Starting Worker plugin PreImport-60f30b73-2f7d-45c2-8309-fea6788e51b0
2023-06-22 22:25:49,339 - distributed.worker - INFO - Starting Worker plugin CPUAffinity-81e91fb6-6a22-4e73-b8b0-2da36ea76698
2023-06-22 22:25:49,339 - distributed.worker - INFO - Starting Worker plugin RMMSetup-1ff5cc98-54b3-40f9-9836-05ba668baa3c
2023-06-22 22:25:49,340 - distributed.worker - INFO -       Start worker at:  tcp://10.33.227.169:32829
2023-06-22 22:25:49,340 - distributed.worker - INFO -          Listening to:  tcp://10.33.227.169:32829
2023-06-22 22:25:49,340 - distributed.worker - INFO -          dashboard at:        10.33.227.169:37091
2023-06-22 22:25:49,340 - distributed.worker - INFO - Waiting to connect to:   tcp://10.33.227.169:8786
2023-06-22 22:25:49,340 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 22:25:49,340 - distributed.worker - INFO -               Threads:                          1
2023-06-22 22:25:49,340 - distributed.worker - INFO -                Memory:                  62.97 GiB
2023-06-22 22:25:49,340 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-a8jjkj2o
2023-06-22 22:25:49,341 - distributed.worker - INFO - Starting Worker plugin RMMSetup-7c3b661a-9e20-44fd-820a-1bc3c0047d47
2023-06-22 22:25:49,351 - distributed.worker - INFO -       Start worker at:  tcp://10.33.227.169:46311
2023-06-22 22:25:49,351 - distributed.worker - INFO -          Listening to:  tcp://10.33.227.169:46311
2023-06-22 22:25:49,351 - distributed.worker - INFO -          dashboard at:        10.33.227.169:42243
2023-06-22 22:25:49,351 - distributed.worker - INFO - Waiting to connect to:   tcp://10.33.227.169:8786
2023-06-22 22:25:49,351 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 22:25:49,351 - distributed.worker - INFO -               Threads:                          1
2023-06-22 22:25:49,359 - distributed.worker - INFO -                Memory:                  62.97 GiB
2023-06-22 22:25:49,359 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-nzti8g7p
2023-06-22 22:25:49,360 - distributed.worker - INFO - Starting Worker plugin PreImport-d96d96a7-bd03-425b-836b-618559fc6505
2023-06-22 22:25:49,360 - distributed.worker - INFO - Starting Worker plugin CPUAffinity-a3bd7661-ac91-4765-83f5-023e5ce34752
2023-06-22 22:25:49,360 - distributed.worker - INFO - Starting Worker plugin RMMSetup-77928a14-73ae-4d40-81e0-cfda20e1d407
2023-06-22 22:25:49,456 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 22:25:49,467 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 22:25:49,469 - distributed.worker - INFO -         Registered to:   tcp://10.33.227.169:8786
2023-06-22 22:25:49,469 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 22:25:49,471 - distributed.core - INFO - Starting established connection to tcp://10.33.227.169:8786
2023-06-22 22:25:49,476 - distributed.worker - INFO -         Registered to:   tcp://10.33.227.169:8786
2023-06-22 22:25:49,476 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 22:25:49,478 - distributed.core - INFO - Starting established connection to tcp://10.33.227.169:8786
2023-06-22 22:25:49,521 - distributed.worker - INFO - Starting Worker plugin CPUAffinity-241d95c2-d741-4788-9fc6-5e79afba6c05
2023-06-22 22:25:49,521 - distributed.worker - INFO - Starting Worker plugin PreImport-5d55b0fa-4511-46af-bcbc-377d931fdf6e
2023-06-22 22:25:49,521 - distributed.worker - INFO - Starting Worker plugin PreImport-ac0a2bdd-997d-4722-9d6c-a411ec606aa9
2023-06-22 22:25:49,522 - distributed.worker - INFO - Starting Worker plugin CPUAffinity-7e83eef2-b622-449c-b98c-4ee191e01412
2023-06-22 22:25:49,522 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 22:25:49,522 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 22:25:49,524 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 22:25:49,530 - distributed.worker - INFO -         Registered to:   tcp://10.33.227.169:8786
2023-06-22 22:25:49,530 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 22:25:49,532 - distributed.core - INFO - Starting established connection to tcp://10.33.227.169:8786
2023-06-22 22:25:49,534 - distributed.worker - INFO -         Registered to:   tcp://10.33.227.169:8786
2023-06-22 22:25:49,534 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 22:25:49,536 - distributed.worker - INFO -         Registered to:   tcp://10.33.227.169:8786
2023-06-22 22:25:49,536 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 22:25:49,537 - distributed.core - INFO - Starting established connection to tcp://10.33.227.169:8786
2023-06-22 22:25:49,538 - distributed.core - INFO - Starting established connection to tcp://10.33.227.169:8786
2023-06-22 22:25:49,558 - distributed.worker - INFO - Starting Worker plugin PreImport-02e4b63c-4bd5-4de8-bc6b-2506a742d114
2023-06-22 22:25:49,558 - distributed.worker - INFO - Starting Worker plugin CPUAffinity-a97fc983-362d-45bc-ace2-6102a9ccdfcb
2023-06-22 22:25:49,559 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 22:25:49,559 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 22:25:49,567 - distributed.worker - INFO -         Registered to:   tcp://10.33.227.169:8786
2023-06-22 22:25:49,567 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 22:25:49,569 - distributed.core - INFO - Starting established connection to tcp://10.33.227.169:8786
2023-06-22 22:25:49,570 - distributed.worker - INFO -         Registered to:   tcp://10.33.227.169:8786
2023-06-22 22:25:49,570 - distributed.worker - INFO - -------------------------------------------------
2023-06-22 22:25:49,571 - distributed.core - INFO - Starting established connection to tcp://10.33.227.169:8786
2023-06-22 22:25:52,388 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 22:25:52,388 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 22:25:52,388 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 22:25:52,389 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 22:25:52,389 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 22:25:52,389 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 22:25:52,389 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 22:25:52,393 - distributed.worker - INFO - Run out-of-band function '_func_ucp_listener_port'
2023-06-22 22:25:52,486 - distributed.worker - INFO - Run out-of-band function '_func_init_all'
2023-06-22 22:25:52,486 - distributed.worker - INFO - Run out-of-band function '_func_init_all'
2023-06-22 22:25:52,486 - distributed.worker - INFO - Run out-of-band function '_func_init_all'
2023-06-22 22:25:52,486 - distributed.worker - INFO - Run out-of-band function '_func_init_all'
2023-06-22 22:25:52,486 - distributed.worker - INFO - Run out-of-band function '_func_init_all'
2023-06-22 22:25:52,486 - distributed.worker - INFO - Run out-of-band function '_func_init_all'
2023-06-22 22:25:52,486 - distributed.worker - INFO - Run out-of-band function '_func_init_all'
2023-06-22 22:25:52,486 - distributed.worker - INFO - Run out-of-band function '_func_init_all'
2023-06-22 22:26:03,529 - distributed.worker - INFO - Run out-of-band function '_subcomm_init'
2023-06-22 22:26:03,669 - distributed.worker - INFO - Run out-of-band function '_subcomm_init'
2023-06-22 22:26:03,673 - distributed.worker - INFO - Run out-of-band function '_subcomm_init'
2023-06-22 22:26:03,695 - distributed.worker - INFO - Run out-of-band function '_subcomm_init'
2023-06-22 22:26:03,712 - distributed.worker - INFO - Run out-of-band function '_subcomm_init'
2023-06-22 22:26:03,781 - distributed.worker - INFO - Run out-of-band function '_subcomm_init'
2023-06-22 22:26:03,859 - distributed.worker - INFO - Run out-of-band function '_subcomm_init'
2023-06-22 22:26:04,072 - distributed.worker - INFO - Run out-of-band function '_subcomm_init'
2023-06-22 22:26:10,157 - distributed.core - INFO - Event loop was unresponsive in Worker for 16.11s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2023-06-22 22:26:10,159 - distributed.core - INFO - Event loop was unresponsive in Worker for 16.10s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2023-06-22 22:26:10,207 - distributed.core - INFO - Event loop was unresponsive in Worker for 16.16s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2023-06-22 22:26:10,207 - distributed.core - INFO - Event loop was unresponsive in Worker for 16.15s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2023-06-22 22:26:10,208 - distributed.core - INFO - Event loop was unresponsive in Worker for 16.14s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2023-06-22 22:26:10,210 - distributed.core - INFO - Event loop was unresponsive in Worker for 16.15s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2023-06-22 22:26:10,210 - distributed.core - INFO - Event loop was unresponsive in Worker for 16.14s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2023-06-22 22:26:10,211 - distributed.core - INFO - Event loop was unresponsive in Worker for 16.16s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2023-06-22 22:26:44,104 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 22:26:44,104 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 22:26:44,108 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 22:26:44,108 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 22:26:44,109 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 22:26:44,109 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 22:26:44,109 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 22:26:44,110 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 22:26:44,618 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 22:26:44,618 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 22:26:44,618 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 22:26:44,618 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 22:26:44,618 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 22:26:44,618 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 22:26:44,618 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 22:26:44,619 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 22:26:45,078 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 22:26:45,078 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 22:26:45,078 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 22:26:45,078 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 22:26:45,078 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 22:26:45,078 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 22:26:45,263 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 22:26:45,264 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 22:26:45,521 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 22:26:45,521 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 22:26:45,521 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 22:26:45,522 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 22:26:45,522 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 22:26:45,522 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 22:26:45,726 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 22:26:45,726 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 22:26:45,965 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 22:26:45,965 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 22:26:45,965 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 22:26:45,965 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 22:26:45,965 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 22:26:45,966 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 22:26:46,172 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 22:26:46,173 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 22:26:46,424 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 22:26:46,424 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 22:26:46,424 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 22:26:46,424 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 22:26:46,424 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 22:26:46,425 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 22:26:46,630 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 22:26:46,630 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 22:26:46,884 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 22:26:46,884 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 22:26:46,884 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 22:26:46,885 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 22:26:46,885 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 22:26:46,885 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 22:26:47,087 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 22:26:47,087 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 22:26:47,324 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 22:26:47,325 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 22:26:47,325 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 22:26:47,325 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 22:26:47,325 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 22:26:47,532 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 22:26:47,532 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 22:26:47,532 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 22:26:47,827 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 22:26:47,827 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 22:26:47,827 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 22:26:47,827 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 22:26:47,827 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 22:26:47,828 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 22:26:48,034 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 22:26:48,034 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 22:26:48,288 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 22:26:48,288 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 22:26:48,288 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 22:26:48,288 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 22:26:48,479 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 22:26:48,479 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 22:26:48,479 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 22:26:48,480 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 22:26:48,773 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 22:26:48,773 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 22:26:48,773 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 22:26:48,773 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 22:26:48,773 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 22:26:48,773 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 22:26:48,973 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 22:26:48,973 - distributed.worker - INFO - Run out-of-band function 'collect'
2023-06-22 22:26:50,057 - distributed.worker - INFO - Run out-of-band function '_func_destroy_all'
2023-06-22 22:26:50,057 - distributed.worker - INFO - Run out-of-band function '_func_destroy_all'
2023-06-22 22:26:50,057 - distributed.worker - INFO - Run out-of-band function '_func_destroy_all'
2023-06-22 22:26:50,057 - distributed.worker - INFO - Run out-of-band function '_func_destroy_all'
2023-06-22 22:26:50,058 - distributed.worker - INFO - Run out-of-band function '_func_destroy_all'
2023-06-22 22:26:50,058 - distributed.worker - INFO - Run out-of-band function '_func_destroy_all'
2023-06-22 22:26:50,058 - distributed.worker - INFO - Run out-of-band function '_func_destroy_all'
2023-06-22 22:26:50,058 - distributed.worker - INFO - Run out-of-band function '_func_destroy_all'
2023-06-22 22:32:54,022 - distributed.worker - INFO - Stopping worker at tcp://10.33.227.169:45315. Reason: worker-handle-scheduler-connection-broken
2023-06-22 22:32:54,022 - distributed.worker - INFO - Stopping worker at tcp://10.33.227.169:36975. Reason: worker-handle-scheduler-connection-broken
2023-06-22 22:32:54,022 - distributed.worker - INFO - Stopping worker at tcp://10.33.227.169:33975. Reason: worker-handle-scheduler-connection-broken
2023-06-22 22:32:54,022 - distributed.worker - INFO - Stopping worker at tcp://10.33.227.169:34491. Reason: worker-close
2023-06-22 22:32:54,022 - distributed.worker - INFO - Stopping worker at tcp://10.33.227.169:33069. Reason: worker-handle-scheduler-connection-broken
2023-06-22 22:32:54,022 - distributed.worker - INFO - Stopping worker at tcp://10.33.227.169:46311. Reason: worker-handle-scheduler-connection-broken
2023-06-22 22:32:54,023 - distributed.worker - INFO - Stopping worker at tcp://10.33.227.169:32829. Reason: worker-handle-scheduler-connection-broken
2023-06-22 22:32:54,023 - distributed.worker - INFO - Stopping worker at tcp://10.33.227.169:42833. Reason: worker-handle-scheduler-connection-broken
2023-06-22 22:32:54,023 - distributed.nanny - INFO - Closing Nanny at 'tcp://10.33.227.169:41969'. Reason: nanny-close
2023-06-22 22:32:54,025 - distributed.nanny - INFO - Nanny asking worker to close. Reason: nanny-close
2023-06-22 22:32:54,026 - distributed.nanny - INFO - Closing Nanny at 'tcp://10.33.227.169:39821'. Reason: nanny-close
2023-06-22 22:32:54,027 - distributed.nanny - INFO - Nanny asking worker to close. Reason: nanny-close
2023-06-22 22:32:54,027 - distributed.nanny - INFO - Closing Nanny at 'tcp://10.33.227.169:46059'. Reason: nanny-close
2023-06-22 22:32:54,027 - distributed.nanny - INFO - Nanny asking worker to close. Reason: nanny-close
2023-06-22 22:32:54,028 - distributed.nanny - INFO - Closing Nanny at 'tcp://10.33.227.169:44281'. Reason: nanny-close
2023-06-22 22:32:54,028 - distributed.nanny - INFO - Nanny asking worker to close. Reason: nanny-close
2023-06-22 22:32:54,025 - distributed.batched - INFO - Batched Comm Closed <TCP (closed) Worker->Scheduler local=tcp://10.33.227.169:59954 remote=tcp://10.33.227.169:8786>
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/base_events.py", line 1871, in _run_once
    event_list = self._selector.select(timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/selectors.py", line 469, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/batched.py", line 115, in _background_send
    nbytes = yield coro
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/tornado/gen.py", line 767, in run
    value = future.result()
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/tcp.py", line 269, in write
    raise CommClosedError()
distributed.comm.core.CommClosedError
2023-06-22 22:32:54,028 - distributed.nanny - INFO - Closing Nanny at 'tcp://10.33.227.169:41851'. Reason: nanny-close
2023-06-22 22:32:54,029 - distributed.nanny - INFO - Nanny asking worker to close. Reason: nanny-close
2023-06-22 22:32:54,029 - distributed.nanny - INFO - Closing Nanny at 'tcp://10.33.227.169:42097'. Reason: nanny-close
2023-06-22 22:32:54,029 - distributed.nanny - INFO - Nanny asking worker to close. Reason: nanny-close
2023-06-22 22:32:54,030 - distributed.nanny - INFO - Closing Nanny at 'tcp://10.33.227.169:43831'. Reason: nanny-close
2023-06-22 22:32:54,030 - distributed.nanny - INFO - Nanny asking worker to close. Reason: nanny-close
2023-06-22 22:32:54,031 - distributed.nanny - INFO - Closing Nanny at 'tcp://10.33.227.169:40591'. Reason: nanny-close
2023-06-22 22:32:54,031 - distributed.nanny - INFO - Nanny asking worker to close. Reason: nanny-close
2023-06-22 22:32:54,045 - distributed.worker - ERROR - Timed out during handshake while connecting to tcp://10.33.227.169:42097 after 100 s
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/base_events.py", line 1871, in _run_once
    event_list = self._selector.select(timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/selectors.py", line 469, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/core.py", line 373, in connect
    handshake = await wait_for(comm.read(), time_left())
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/utils.py", line 1878, in wait_for
    return await asyncio.wait_for(fut, timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/tcp.py", line 241, in read
    convert_stream_closed_error(self, e)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed)  local=tcp://10.33.227.169:44274 remote=tcp://10.33.227.169:42097>: ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/utils.py", line 754, in wrapper
    return await func(*args, **kwargs)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/worker.py", line 1540, in close
    await r.close_gracefully(reason=reason)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/core.py", line 1362, in send_recv_from_rpc
    comm = await self.pool.connect(self.addr)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/core.py", line 1606, in connect
    return await connect_attempt
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/core.py", line 1527, in _connect
    comm = await connect(
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/core.py", line 378, in connect
    raise OSError(
OSError: Timed out during handshake while connecting to tcp://10.33.227.169:42097 after 100 s
2023-06-22 22:32:54,050 - distributed.worker - ERROR - Timed out during handshake while connecting to tcp://10.33.227.169:46059 after 100 s
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/base_events.py", line 1871, in _run_once
    event_list = self._selector.select(timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/selectors.py", line 469, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/core.py", line 373, in connect
    handshake = await wait_for(comm.read(), time_left())
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/utils.py", line 1878, in wait_for
    return await asyncio.wait_for(fut, timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/tcp.py", line 241, in read
    convert_stream_closed_error(self, e)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed)  local=tcp://10.33.227.169:51652 remote=tcp://10.33.227.169:46059>: ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/utils.py", line 754, in wrapper
    return await func(*args, **kwargs)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/worker.py", line 1540, in close
    await r.close_gracefully(reason=reason)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/core.py", line 1362, in send_recv_from_rpc
    comm = await self.pool.connect(self.addr)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/core.py", line 1606, in connect
    return await connect_attempt
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/core.py", line 1527, in _connect
    comm = await connect(
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/core.py", line 378, in connect
    raise OSError(
OSError: Timed out during handshake while connecting to tcp://10.33.227.169:46059 after 100 s
2023-06-22 22:32:54,052 - distributed.worker - ERROR - Timed out during handshake while connecting to tcp://10.33.227.169:40591 after 100 s
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/base_events.py", line 1871, in _run_once
    event_list = self._selector.select(timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/selectors.py", line 469, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/core.py", line 373, in connect
    handshake = await wait_for(comm.read(), time_left())
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/utils.py", line 1878, in wait_for
    return await asyncio.wait_for(fut, timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/tcp.py", line 241, in read
    convert_stream_closed_error(self, e)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed)  local=tcp://10.33.227.169:46982 remote=tcp://10.33.227.169:40591>: ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/utils.py", line 754, in wrapper
    return await func(*args, **kwargs)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/worker.py", line 1540, in close
    await r.close_gracefully(reason=reason)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/core.py", line 1362, in send_recv_from_rpc
    comm = await self.pool.connect(self.addr)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/core.py", line 1606, in connect
    return await connect_attempt
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/core.py", line 1527, in _connect
    comm = await connect(
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/core.py", line 378, in connect
    raise OSError(
OSError: Timed out during handshake while connecting to tcp://10.33.227.169:40591 after 100 s
2023-06-22 22:32:54,052 - distributed.worker - ERROR - Timed out during handshake while connecting to tcp://10.33.227.169:44281 after 100 s
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/base_events.py", line 1871, in _run_once
    event_list = self._selector.select(timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/selectors.py", line 469, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/core.py", line 373, in connect
    handshake = await wait_for(comm.read(), time_left())
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/utils.py", line 1878, in wait_for
    return await asyncio.wait_for(fut, timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/tcp.py", line 241, in read
    convert_stream_closed_error(self, e)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed)  local=tcp://10.33.227.169:51766 remote=tcp://10.33.227.169:44281>: ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/utils.py", line 754, in wrapper
    return await func(*args, **kwargs)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/worker.py", line 1540, in close
    await r.close_gracefully(reason=reason)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/core.py", line 1362, in send_recv_from_rpc
    comm = await self.pool.connect(self.addr)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/core.py", line 1606, in connect
    return await connect_attempt
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/core.py", line 1527, in _connect
    comm = await connect(
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/core.py", line 378, in connect
    raise OSError(
OSError: Timed out during handshake while connecting to tcp://10.33.227.169:44281 after 100 s
2023-06-22 22:32:54,054 - distributed.core - ERROR - Timed out during handshake while connecting to tcp://10.33.227.169:41851 after 100 s
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/base_events.py", line 1871, in _run_once
    event_list = self._selector.select(timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/selectors.py", line 469, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/core.py", line 373, in connect
    handshake = await wait_for(comm.read(), time_left())
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/utils.py", line 1878, in wait_for
    return await asyncio.wait_for(fut, timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/tcp.py", line 241, in read
    convert_stream_closed_error(self, e)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed)  local=tcp://10.33.227.169:43296 remote=tcp://10.33.227.169:41851>: ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/utils.py", line 754, in wrapper
    return await func(*args, **kwargs)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/worker.py", line 1540, in close
    await r.close_gracefully(reason=reason)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/core.py", line 1362, in send_recv_from_rpc
    comm = await self.pool.connect(self.addr)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/core.py", line 1606, in connect
    return await connect_attempt
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/core.py", line 1527, in _connect
    comm = await connect(
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/core.py", line 378, in connect
    raise OSError(
OSError: Timed out during handshake while connecting to tcp://10.33.227.169:41851 after 100 s
2023-06-22 22:32:54,053 - distributed.worker - ERROR - Timed out during handshake while connecting to tcp://10.33.227.169:39821 after 100 s
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/base_events.py", line 1871, in _run_once
    event_list = self._selector.select(timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/selectors.py", line 469, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/core.py", line 373, in connect
    handshake = await wait_for(comm.read(), time_left())
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/utils.py", line 1878, in wait_for
    return await asyncio.wait_for(fut, timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/tcp.py", line 241, in read
    convert_stream_closed_error(self, e)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed)  local=tcp://10.33.227.169:59788 remote=tcp://10.33.227.169:39821>: ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/utils.py", line 754, in wrapper
    return await func(*args, **kwargs)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/worker.py", line 1540, in close
    await r.close_gracefully(reason=reason)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/core.py", line 1362, in send_recv_from_rpc
    comm = await self.pool.connect(self.addr)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/core.py", line 1606, in connect
    return await connect_attempt
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/core.py", line 1527, in _connect
    comm = await connect(
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/core.py", line 378, in connect
    raise OSError(
OSError: Timed out during handshake while connecting to tcp://10.33.227.169:39821 after 100 s
2023-06-22 22:32:54,054 - distributed.worker - ERROR - Timed out during handshake while connecting to tcp://10.33.227.169:43831 after 100 s
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/base_events.py", line 1871, in _run_once
    event_list = self._selector.select(timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/selectors.py", line 469, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/core.py", line 373, in connect
    handshake = await wait_for(comm.read(), time_left())
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/utils.py", line 1878, in wait_for
    return await asyncio.wait_for(fut, timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/tcp.py", line 241, in read
    convert_stream_closed_error(self, e)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed)  local=tcp://10.33.227.169:53456 remote=tcp://10.33.227.169:43831>: ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/utils.py", line 754, in wrapper
    return await func(*args, **kwargs)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/worker.py", line 1540, in close
    await r.close_gracefully(reason=reason)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/core.py", line 1362, in send_recv_from_rpc
    comm = await self.pool.connect(self.addr)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/core.py", line 1606, in connect
    return await connect_attempt
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/core.py", line 1527, in _connect
    comm = await connect(
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/comm/core.py", line 378, in connect
    raise OSError(
OSError: Timed out during handshake while connecting to tcp://10.33.227.169:43831 after 100 s
2023-06-22 22:32:57,233 - distributed.nanny - WARNING - Worker process still alive after 3.1999742126464845 seconds, killing
2023-06-22 22:32:57,233 - distributed.nanny - WARNING - Worker process still alive after 3.1999992370605472 seconds, killing
2023-06-22 22:32:57,234 - distributed.nanny - WARNING - Worker process still alive after 3.199999389648438 seconds, killing
2023-06-22 22:32:57,234 - distributed.nanny - WARNING - Worker process still alive after 3.1999995422363288 seconds, killing
2023-06-22 22:32:57,235 - distributed.nanny - WARNING - Worker process still alive after 3.199999389648438 seconds, killing
2023-06-22 22:32:57,236 - distributed.nanny - WARNING - Worker process still alive after 3.199999389648438 seconds, killing
2023-06-22 22:32:57,236 - distributed.nanny - WARNING - Worker process still alive after 3.1999995422363288 seconds, killing
2023-06-22 22:32:57,237 - distributed.nanny - WARNING - Worker process still alive after 3.1999995422363288 seconds, killing
2023-06-22 22:32:57,976 - distributed.nanny - INFO - Worker process 1466626 was killed by signal 9
2023-06-22 22:32:58,026 - distributed.nanny - ERROR - Error in Nanny killing Worker subprocess
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 597, in close
    await self.kill(timeout=timeout, reason=reason)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 380, in kill
    await self.process.kill(reason=reason, timeout=0.8 * (deadline - time()))
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 853, in kill
    await process.join(max(0, deadline - time()))
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/process.py", line 330, in join
    await wait_for(asyncio.shield(self._exit_future), timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/utils.py", line 1878, in wait_for
    return await asyncio.wait_for(fut, timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
2023-06-22 22:32:58,029 - distributed.nanny - ERROR - Error in Nanny killing Worker subprocess
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 597, in close
    await self.kill(timeout=timeout, reason=reason)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 380, in kill
    await self.process.kill(reason=reason, timeout=0.8 * (deadline - time()))
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 853, in kill
    await process.join(max(0, deadline - time()))
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/process.py", line 330, in join
    await wait_for(asyncio.shield(self._exit_future), timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/utils.py", line 1878, in wait_for
    return await asyncio.wait_for(fut, timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
2023-06-22 22:32:58,029 - distributed.nanny - ERROR - Error in Nanny killing Worker subprocess
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 597, in close
    await self.kill(timeout=timeout, reason=reason)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 380, in kill
    await self.process.kill(reason=reason, timeout=0.8 * (deadline - time()))
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 853, in kill
    await process.join(max(0, deadline - time()))
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/process.py", line 330, in join
    await wait_for(asyncio.shield(self._exit_future), timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/utils.py", line 1878, in wait_for
    return await asyncio.wait_for(fut, timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
2023-06-22 22:32:58,029 - distributed.nanny - ERROR - Error in Nanny killing Worker subprocess
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 597, in close
    await self.kill(timeout=timeout, reason=reason)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 380, in kill
    await self.process.kill(reason=reason, timeout=0.8 * (deadline - time()))
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 853, in kill
    await process.join(max(0, deadline - time()))
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/process.py", line 330, in join
    await wait_for(asyncio.shield(self._exit_future), timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/utils.py", line 1878, in wait_for
    return await asyncio.wait_for(fut, timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
2023-06-22 22:32:58,030 - distributed.nanny - ERROR - Error in Nanny killing Worker subprocess
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 597, in close
    await self.kill(timeout=timeout, reason=reason)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 380, in kill
    await self.process.kill(reason=reason, timeout=0.8 * (deadline - time()))
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 853, in kill
    await process.join(max(0, deadline - time()))
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/process.py", line 330, in join
    await wait_for(asyncio.shield(self._exit_future), timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/utils.py", line 1878, in wait_for
    return await asyncio.wait_for(fut, timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
2023-06-22 22:32:58,030 - distributed.nanny - ERROR - Error in Nanny killing Worker subprocess
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 597, in close
    await self.kill(timeout=timeout, reason=reason)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 380, in kill
    await self.process.kill(reason=reason, timeout=0.8 * (deadline - time()))
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 853, in kill
    await process.join(max(0, deadline - time()))
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/process.py", line 330, in join
    await wait_for(asyncio.shield(self._exit_future), timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/utils.py", line 1878, in wait_for
    return await asyncio.wait_for(fut, timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
2023-06-22 22:32:58,032 - distributed.nanny - ERROR - Error in Nanny killing Worker subprocess
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 597, in close
    await self.kill(timeout=timeout, reason=reason)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 380, in kill
    await self.process.kill(reason=reason, timeout=0.8 * (deadline - time()))
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/nanny.py", line 853, in kill
    await process.join(max(0, deadline - time()))
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/process.py", line 330, in join
    await wait_for(asyncio.shield(self._exit_future), timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/site-packages/distributed/utils.py", line 1878, in wait_for
    return await asyncio.wait_for(fut, timeout)
  File "/opt/conda/envs/rapids/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
2023-06-22 22:32:58,033 - distributed.process - INFO - reaping stray process <SpawnProcess name='Dask Worker process (from Nanny)' pid=1466628 parent=1466565 started daemon>
2023-06-22 22:32:58,033 - distributed.process - INFO - reaping stray process <SpawnProcess name='Dask Worker process (from Nanny)' pid=1466622 parent=1466565 started daemon>
2023-06-22 22:32:58,033 - distributed.process - INFO - reaping stray process <SpawnProcess name='Dask Worker process (from Nanny)' pid=1466619 parent=1466565 started daemon>
2023-06-22 22:32:58,034 - distributed.process - INFO - reaping stray process <SpawnProcess name='Dask Worker process (from Nanny)' pid=1466616 parent=1466565 started daemon>
2023-06-22 22:32:58,034 - distributed.process - INFO - reaping stray process <SpawnProcess name='Dask Worker process (from Nanny)' pid=1466613 parent=1466565 started daemon>
2023-06-22 22:32:58,034 - distributed.process - INFO - reaping stray process <SpawnProcess name='Dask Worker process (from Nanny)' pid=1466610 parent=1466565 started daemon>
2023-06-22 22:32:58,034 - distributed.process - INFO - reaping stray process <SpawnProcess name='Dask Worker process (from Nanny)' pid=1466607 parent=1466565 started daemon>
2023-06-22 22:32:58,661 - distributed.process - WARNING - [<AsyncProcess Dask Worker process (from Nanny)>] process 1466613 exit status was already read will report exitcode 255
2023-06-22 22:32:58,933 - distributed.process - WARNING - [<AsyncProcess Dask Worker process (from Nanny)>] process 1466628 exit status was already read will report exitcode 255
